### ISSUE TITLE
Issues to create stellard instance

### ISSUE THREAD

**Issue by muralisrinivas1234** [stellar/stellard#196]
I am new to stellar and working on an financial project . I am trying to create a stellard instance following your intstructions. When creating CLI tests "npm test" is giving errors.I am herewith sending a file containing the errors
![screenshot from 2018-04-25 16-10-36](https://user-images.githubusercontent.com/37139818/39241059-5310b840-48a3-11e8-94a4-0704edc13fb4.png)

**Comment by bartekn** [comment]
stellard is deprecated project. Please check [stellar-core](https://github.com/stellar/stellar-core).
